def generate_report(insights):
    """
    Formats business insights into a simple SME report
    """

    report = "\n".join([
        "=== SME WEEKLY HEALTH REPORT ===",
        "",
        *insights,
        "",
        "Generated by SME Health Report AI"
    ])

    return report
